// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwTRAkAkb4HZAv--THzM1cCBVdVF3PCNY',
    appId: '1:287946113595:android:ce734a12d1b824adcb121e',
    messagingSenderId: '287946113595',
    projectId: 'nutanvij-electricals',
    databaseURL: 'https://nutanvij-electricals-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutanvij-electricals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3okrtKFLn5HNk6ewCmvWQBtlRA0AHKls',
    appId: '1:287946113595:ios:ed6f9bb8850410a9cb121e',
    messagingSenderId: '287946113595',
    projectId: 'nutanvij-electricals',
    databaseURL: 'https://nutanvij-electricals-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutanvij-electricals.firebasestorage.app',
    iosBundleId: 'com.nepl.nutanvijElectricals',
  );

}